FROM i386/golang:1.16.2-buster as build

# Add QEMU
COPY qemu-i386-static /usr/bin/qemu-i386-static
#RUN  chmod +x /usr/bin/qemu-i386-static

WORKDIR /src

# go.mod and go.sum if exists
#COPY go.* ./
COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=386 GO111MODULE=off go build -v -ldflags="-s -w" -o hello-linux-386; chmod +x hello-linux-386; ls -l /src; 


FROM i386/debian:buster

COPY --from=build  /src/hello-linux-386 /usr/bin/hello

CMD [ "/usr/bin/hello" ]
