#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-spec multi-arch-manifest.yaml


# BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)
# echo "${BUILD_ARCH}"

# [ "${BUILD_ARCH}" == "Dockerfile" ] && { echo 'qemu-user-static: Download not required for current arch'; exit 0; }

# if [ "${BUILD_ARCH}" == "arm64v8" ]; then
#     echo 'arm64'
#     ./manifest-tool push from-args --platforms linux/arm64/v8 --template dyrnq/multiarch-hello:ARCHVARIANT --target dyrnq/multiarch-hello:latest
# elif [ "${BUILD_ARCH}" == "i386" ]; then
#     echo 'i386'
#     ./manifest-tool push from-args --platforms linux/386 --template dyrnq/multiarch-hello:ARCH --target dyrnq/multiarch-hello:latest
# else
#     echo 'arm'
#     ./manifest-tool push from-args --platforms linux/arm/v7 --template dyrnq/multiarch-hello:ARCH32VARIANT --target dyrnq/multiarch-hello:latest
# fi